services:
  - type: web
    name: rasa-api
    rootDir: .
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: rasa run --enable-api --cors "*" --model models --port $PORT
    envVars:
      - key: PORT
        value: 5005
      - key: ACTION_SERVER_HOSTPORT
        fromService:
          type: pserv
          name: rasa-actions
          property: hostport

  - type: pserv
    name: rasa-actions
    rootDir: .
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: rasa run actions --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 5055

  - type: web
    name: line-bridge
    rootDir: rasa-line-bot
    runtime: node
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: LINE_ACCESS_TOKEN
        sync: false
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: RASA_HOSTPORT
        fromService:
          type: web
          name: rasa-api
          property: hostport
